### ISSUE TITLE
Ejercicio 2. De forma individual para todos

### ISSUE THREAD

**Issue by FedeBirge** [ISPC-TST-Sensores-y-Actuadores/practica-de-la-4ta-semana-grupo-4#2]

**Comment by FedeBirge** [comment]
éste ejercicio está en el aula virtual para hacerlo de manera individual

**Comment by LitoCarunchio** [comment]
creadas las cuentas necesarias

**Comment by GiseRomero** [comment]
Hola chicos! creadas las cuentas y vistos los videos

**Comment by FedeBirge** [comment]
Tarea realizada de mi parte también!

**Comment by Emygut** [comment]
Tarea realizada visto los videos y creada la cuenta en AWS.
